### PR TITLE
Enable triangle functions

### PR DESCRIPTION
**Pull request by leon-vv**
Hi there! This is a follow up on issue #19. I would be interested in enabling the support for the triangle function of FMMLIB3D. Could you let me know if this PR is what you expect?

Thanks!

### CODE REVIEW

**Comment by inducer** [comment]
Thanks for the contribution! Could you look into the CI failures?

**Comment by leon-vv** [comment]
Hi, I tried to fix the errors. I had to change a workflow file, but I don't think the change is reflected in the actual workflow until you accept the PR. So the workflow will keep failing

**Comment by inducer** [comment]
Changes to workflow files take effect even pre-merge, so this should be all good. Could you look at the linter failure and also make the equivalent change to `.gitlab-ci.yml`? (For mostly historical reasons, we maintain two separate CI systems. The other lives at https://gitlab.tiker.net/inducer/pyfmmlib)

**Comment by leon-vv** [comment]
I made another attempt, let's see if this fixed it

**Comment by inducer** [comment]
LGTM! Thanks for your contribution.

**Pull request merged**
